name: Bug report
description: |
  You are experiencing an issue with helix.go that is different than the
  documented or expected behavior

body:
  - type: dropdown
    attributes:
      label: What helix version are you using?
      options:
        - 0.14.x
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What OS are you running?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What architecture are you running?
      options:
        - amd64
        - arm64
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What Go version are you running?
      options:
        - 1.21.x
        - 1.20.x
        - 1.19.x
        - 1.18.x
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What integrations are impacted by this problem?
      description: Select none if this applies to the core or the entire ecosystem.
      multiple: true
      options:
        - clickhouse
        - nats
        - postgres
        - rest
        - temporal
        - vault
  - type: textarea
    attributes:
      label: Unexpected behavior
      value: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: Please indicate the steps needed to reproduce the previously described behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      value: Please describe the behavior you were expected.
  - type: textarea
    attributes:
      label: Logs
      value: You can provide logs (if applicable) so we can better adress your issue.
